### ISSUE TITLE
Cannot resolve 'file' or 'directory' react/lib/ReactMount

### ISSUE THREAD

**Issue by pfncfen** [SteamerTeam/steamer-react#11]
After git cloning your repo, I tried npm run dev. Below is the result:

![image](https://cloud.githubusercontent.com/assets/3774176/20589809/c476fb2a-b259-11e6-906e-ddaad4a7d49e.png)

I've searched github and I found this
https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md

> Cannot resolve 'file' or 'directory' react/lib/ReactMount
> 
> If you're using a precompiled React instead of react npm package, React Hot Loader configuration will need a few tweaks. See Usage with External React.
> 
> Make sure you have '.js' in resolve.extensions section of Webpack config, or Webpack won't be able to find any JS files without explicitly specifying extension in require.

According to this, I deleted the react-hot-loader related code in the webpack.dev.js and the whole thing started to functioning again. However I had to give up react-hot-loader which is very useful in my development.

I was thinking that is it because the version of react-hot-loader is out of date so that some function is depracated and the whole thing just crashed down?
If u know the answer, please reply ASAP. Thx.

**Comment by pfncfen** [comment]
https://github.com/gaearon/react-hot-loader/issues/417

https://segmentfault.com/q/1010000007515184

some info u may concern

**Comment by lcxfs1991** [comment]
Hi @pfncfen. Thank u for your response. I am at Singapore preparing for a sharing. I would take a look at it at weekends. I would be also appreciated if u can fix the problem. Thanks again!

**Comment by pfncfen** [comment]
Hi @lcxfs1991. Thank u for ur reply. The answer to this question simply lies in my reference 
https://github.com/gaearon/react-hot-loader/issues/417

> Adding alias: { 'react/lib/ReactMount': 'react-dom/lib/ReactMount' } to your webpack config fixes this for now. 

I've tried this, and it worked out. But the author of React-Hot-Loader strongly advised us to upgrade from v1.3.0 to v3.x so maybe it's time to take a look into this.
