### ISSUE TITLE
ERROR in multi index Module not found & ERROR in multi spa

### ISSUE THREAD

**Issue by havefive** [SteamerTeam/steamer-react#5]
Steps:

1. npm install 
2. npm run dev

Error:
ERROR in multi index
Module not found: Error: Cannot resolve module 'react-hot' in /react/steamer-react-react
 @ multi index

ERROR in multi spa
Module not found: Error: Cannot resolve module 'react-hot' in /react/steamer-react-react
 @ multi spa

**Comment by lcxfs1991** [comment]
@havefive let me have a look.

**Comment by lcxfs1991** [comment]
@havefive I repeat ur steps, however I have not encountered any issues. Could u please tell me how u arrange ur node_modules?

or u can add my qq to discuss about it.

My qq: 249806703

**Comment by lcxfs1991** [comment]
what's the issue actually?

**Comment by havefive** [comment]
Sorry for the late reply you，I checked the node_modules，not found react-hot-loader
