### ISSUE TITLE
Module build failed: Error: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by billwing** [SteamerTeam/steamer-react#8]
`npm run dev ` scss构建报错如下：

![image](https://cloud.githubusercontent.com/assets/3411815/17659207/9e37a4fa-6303-11e6-9653-6736b785814b.png)

**Comment by lcxfs1991** [comment]
webpack.dev 里有postcss插件？

**Comment by billwing** [comment]
@lcxfs1991 没有呢，我clone下来没有作改动

**Comment by lcxfs1991** [comment]
@billwing 可加我的qq：249806703详聊

**Comment by lcxfs1991** [comment]
用户安装css-loader有问题。
